version: 2
updates:
- package-ecosystem: npm
  directory: "/cb-sol-cli"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ethers
    versions:
    - 5.0.29
    - 5.0.30
    - 5.0.31
    - 5.0.32
    - 5.1.0
    - 5.1.3
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
- package-ecosystem: gomod
  directory: "/cfgBuilder"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
- package-ecosystem: gomod
  directory: "/deploy-test"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/ethereum/go-ethereum
    versions:
    - 1.10.0
    - 1.10.1
    - 1.9.25
  - dependency-name: github.com/ChainSafe/ChainBridge
    versions:
    - 1.1.0
